// import { Geist, Geist_Mono } from "next/font/google";
"use client"
import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { SessionProvider } from "next-auth/react";
import { CompetitionProvider } from '@/context/CompetitionContext';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="robots" content="noindex, nofollow" />
        <title>Network Hackathon Site</title>
      </head>
      <body>
        <SessionProvider>
        <div className = "biggestWrap">
          <Navbar/>
          <div className = "bigWrap">
            <CompetitionProvider>{children}</CompetitionProvider>
          </div>
          <Footer/>
        </div>
        </SessionProvider>
      </body>
    </html>
  );
}